test-1

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -23,11 +23,13 @@ jobs:
         uses: actions/setup-node@v3
         with:
           node-version: ${{ matrix.node-version }}
-          cache: "npm"
-      - name: Show workspace test
-        run: pwd && ls -la
+          cache: "npm"      
       - name: Install dependencies        
-        run: npm ci
+        # run: npm ci
+        uses: bahmutov/npm-install@v1
+        with:
+          useRollingCache: true
+      - run: npm t
       - run: |
           touch ./.env.dev
           echo "${{ secrets.DEV_ENV_FILE }}" > ./.env.dev
@@ -39,67 +41,69 @@ jobs:
         uses: actions/upload-artifact@v4
         with:
           name: source-code
-          path: .
+          path: |
+            ./
+            !./node_modules
 
-  build-publish:
-    runs-on: self-hosted
-    needs: test
-    steps:
-      - name: Get code from artifact
-        uses: actions/download-artifact@v4
-        with:
-          name: source-code
-      - name: Show workspace build-publish
-        run: pwd && ls -la
-      - name: Log in to Docker Hub 
-        uses: docker/login-action@v3 
-        with: 
-          username: ${{ env.DOCKERHUB_USERNAME }}         
-          password: ${{ secrets.DOCKERHUB_TOKEN }}
-      - name: Setup Docker cache Directory
-        run: |
-          mkdir -p /tmp/docker-cache /tmp/docker-cache-new
-          chmod -R 777 /tmp/docker-cache*
-      - name: Build and push
-        uses: docker/build-push-action@v6 
-        with:
-          context: .
-          push: true
-          tags: |
-            ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
-            ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
-          cache-from: type=local,src=/tmp/docker-cache
-          cache-to: type=local,dest=/tmp/docker-cache-new,mode=max
-          builder: aws-builder
-      - name: Rotate cache
-        if: success()
-        run: |
-          rm -rf /tmp/docker-cache-old
-          mv /tmp/docker-cache /tmp/docker-cache-old
-          mv /tmp/docker-cache-new /tmp/docker-cache
-  deploy: 
-    runs-on: self-hosted
-    needs: build-publish
-    steps:      
-      - name: Stop and remove old container         
-        run: | 
-            docker rm -f ${{ env.IMAGE_NAME }} || true                  
-      - name: Run container
-        run: |          
-          docker run \
-          --name ${{ env.IMAGE_NAME }} \
-          -e "DB_URI=${{ secrets.DB_URI }}" \
-          --restart unless-stopped \
-          -dp 80:3000 ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}      
-  cleanup:
-    runs-on: self-hosted 
-    needs: deploy 
-    if: always()
-    steps: 
-      - name: Prune system          
-        run: |
-          docker system prune -f --filter "until=24h"
-          docker builder prune -f
+  # build-publish:
+  #   runs-on: self-hosted
+  #   needs: test
+  #   steps:
+  #     - name: Get code from artifact
+  #       uses: actions/download-artifact@v4
+  #       with:
+  #         name: source-code
+  #     - name: Show workspace build-publish
+  #       run: pwd && ls -la
+  #     - name: Log in to Docker Hub 
+  #       uses: docker/login-action@v3 
+  #       with: 
+  #         username: ${{ env.DOCKERHUB_USERNAME }}         
+  #         password: ${{ secrets.DOCKERHUB_TOKEN }}
+  #     - name: Setup Docker cache Directory
+  #       run: |
+  #         mkdir -p /tmp/docker-cache /tmp/docker-cache-new
+  #         chmod -R 777 /tmp/docker-cache*
+  #     - name: Build and push
+  #       uses: docker/build-push-action@v6 
+  #       with:
+  #         context: .
+  #         push: true
+  #         tags: |
+  #           ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
+  #           ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
+  #         cache-from: type=local,src=/tmp/docker-cache
+  #         cache-to: type=local,dest=/tmp/docker-cache-new,mode=max
+  #         builder: aws-builder
+  #     - name: Rotate cache
+  #       if: success()
+  #       run: |
+  #         rm -rf /tmp/docker-cache-old
+  #         mv /tmp/docker-cache /tmp/docker-cache-old
+  #         mv /tmp/docker-cache-new /tmp/docker-cache
+  # deploy: 
+  #   runs-on: self-hosted
+  #   needs: build-publish
+  #   steps:      
+  #     - name: Stop and remove old container         
+  #       run: | 
+  #           docker rm -f ${{ env.IMAGE_NAME }} || true                  
+  #     - name: Run container
+  #       run: |          
+  #         docker run \
+  #         --name ${{ env.IMAGE_NAME }} \
+  #         -e "DB_URI=${{ secrets.DB_URI }}" \
+  #         --restart unless-stopped \
+  #         -dp 80:3000 ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}      
+  # cleanup:
+  #   runs-on: self-hosted 
+  #   needs: deploy 
+  #   if: always()
+  #   steps: 
+  #     - name: Prune system          
+  #       run: |
+  #         docker system prune -f --filter "until=24h"
+  #         docker builder prune -f
 
 
   
